# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20161209_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
